### ISSUE TITLE
会則の見直し

### ISSUE THREAD

**Issue by mahya8585** [jjug/jjug-web#50]
気になる部分についてみんなで議論しましょう

**Comment by cero-t** [comment]
```
第 5 条 次の手続きを経て本会の会員になることができる。
1. 所定の入会申込書を本会に提出し、幹事会の承認を得る。

第 7 条 会員が退会しようとする場合は、本会に申し出なければならない。ただし、次の場合は自動的に退会したものとみなす。
1. 会員が死亡した場合

第 35 条 会員は、入会時に本会に届け出た事項について変更があった場合には、速やかに変更内容を届け出なくてはならない。
```
Doorkeeperへの登録をもって会員としているので、表現を見直したほうが良い。
また、死んでも自動退会扱いにはならないので第7条の1も要らない。

```
第 10 条 役員は第 14 条に定める幹事の中より互選によって選出され、第 20 条で定める定期総会において承認されるものとする。
第 10 条の2 JJUG CCC運営委員会の役員は第 14 条に定める幹事の中より互選によって選出され、第 20 条で定める定期総会において承認されるものとする。
```
定期総会は第21条。

```
JJUG CCC運営委員は、幹事が兼任する
JJUG CCC運営委員は、JJUG CCC運営を優先事項として活動する
```
句点がない。

```
また会長は、かかる指名に基づき幹事を選任するため、第23条で定める総会を招集するもとする。
```
会長 → リーダー
総会 → 臨時総会

```
名誉会長は、本会の活動、発展などに特別の功労のあった者から、幹事会の決議に基づき会長が委嘱することができる。
幹事会が名誉会長の解任を決議したときには、会長は名誉会長を解任しなければならない。
```
会長 → リーダー

**Comment by cero-t** [comment]
15条と17条について、どのような表現にするか要相談。

**Comment by mahya8585** [comment]
> 第 5 条 次の手続きを経て本会の会員になることができる。
> 1. 所定の入会申込書を本会に提出し、幹事会の承認を得る。

- Doorkeeper(Doorkeeper.jp)の日本Javaユーザグループのコミュニティへの参加をもって入会とする

> 第 7 条 会員が退会しようとする場合は、本会に申し出なければならない。ただし、次の場合は自動的に退会したものとみなす。
> 1. 会員が死亡した場合

- 会員が退会しようとする場合は、DoorKeeperの日本Javaユーザグループのコミュニティの退会をもって本会を退会とする
- 会員が死亡した場合の項は削除する
- 第7章雑則の35条はそのまま残す

> 第 10 条 役員は第 14 条に定める幹事の中より互選によって選出され、第 20 条で定める定期総会において承認されるものとする。
> 第 10 条の2 JJUG CCC運営委員会の役員は第 14 条に定める幹事の中より互選によって選出され、第 20 条で定める定期総会において承認されるものとする。

- 第 10 条 役員は第 14 条に定める幹事の中より互選によって選出され、**第 21 条**で定める定期総会において承認されるものとする。
- 第 10 条の2 JJUG CCC運営委員会の役員は第 14 条に定める幹事の中より互選によって選出され、**第 21 条**で定める定期総会において承認されるものとする。

-  第 10 条の2のリスト表記1つ目の文末に句点を追加
  -  第 14 条の2も同様

> 第17条の2
> また会長は、かかる指名に基づき幹事を選任するため、第23条で定める総会を招集するもとする。

- また**リーダー**は、かかる指名に基づき幹事を選任するため、第23条で定める**臨時総会**を招集するもとする。

> 18条の2 リスト表記2つめ
> 名誉会長は、本会の活動、発展などに特別の功労のあった者から、幹事会の決議に基づき会長が委嘱することができる。
> 幹事会が名誉会長の解任を決議したときには、会長は名誉会長を解任しなければならない。

- 名誉会長は、本会の活動、発展などに特別の功労のあった者から、幹事会の決議に基づきリーダーが委嘱することができる。幹事会が名誉会長の解任を決議したときには、リーダーは名誉会長を解任しなければならない。

**Comment by mahya8585** [comment]
15条はそのままで。
17条もそのままで。

**Comment by mahya8585** [comment]
修正差分をCCCの総会で提示し、承認もらう

**Comment by yangping0211** [comment]
総会で承認をもらい、マージしたためクローズ。
