### ISSUE TITLE
細則の見直し

### ISSUE THREAD

**Issue by cero-t** [jjug/jjug-web#51]
https://www.java-users.jp/page/rule/
これの後半にある「JJUG 活動および事務局等に関する細則」について。

**Comment by mahya8585** [comment]
事務局先の変更

> 第 2 条 本会は会則第 18 条に定める事務局を以下の住所に置き、本会の所在地とする。
> 横浜市西区みなとみらい3-7-1 オーシャンゲートみなとみらい 8F 株式会社アットウェア内

第 2 条 本会は会則第 18 条に定める事務局を以下の住所に置き、本会の所在地とする。
東京都港区芝五丁目27番6号 泉田町ビル5階 株式会社イーサイド内

**Comment by mahya8585** [comment]
> 第 3 条 事務局長の責務は次の通りとする。
> 1. 総会、幹事会の記録
> 2. 会員、幹事及び役員に対しての必要な事項の伝達
> 3. 会員の入退会手続き及びこれに関する記録
> 4. 本会の会計事務及び記録
> 5. 公的文書の作成
> 6. 事務局の運営及び管理
> 7. その他、本会が必要とする事務処理

- 事務局長は現在存在しているのか？
  - **TODO :** イーサイドに事務局長を1名任命してもらう
- 1～3 は現在事務局長の責務ではない
  - 1～3を削除し4～7の項番を繰り上げる

**Comment by mahya8585** [comment]
> 細則第4条
> 公印(会長印)の管理責任者はリーダーとする。

**公印ないので項まるまる削除する
-> 合わせてそれより下の条数を繰り上げる**

**Comment by mahya8585** [comment]
修正差分をCCCの総会で提示し、承認もらう

**Comment by yangping0211** [comment]
総会で承認をもらい、マージしたためクローズ。
